version: "3.9"

services:
  app:
    build: .
    container_name: topobrainx
    #command: python scripts/run_oinfo_sinfo_triplets_1subject.py
    volumes:
      - .:/app
      - ./results:/app/results
    environment:
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64

